<?php

/**
 * @file
 * Migrate module file
 */

/**
 * Implements hook_migrate_api().
 */
function tr_migrate_migrate_api() {
  $api = array(
    'api' => 2,
    'groups' => array(
      'tr' => array(
        'title' => t('TR Demo Migrations'),
      ),
    ),
    'migrations' => array(
      'TrDemoMigration' => array(
        'class_name' => 'TrDemoMigration',
        'group_name' => 'tr',
      ),
    ),
  );
  return $api;
}
